# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GraystackTemp < Formula
  desc ""
  homepage ""
  version "0.1.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrayFlash/go-releaser/releases/download/v0.1.4/go-releaser_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "0e5733e775d5147cc12995f8f03b609fa2412860701cffdd9f0818f734170f4c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GrayFlash/go-releaser/releases/download/v0.1.4/go-releaser_0.1.4_Linux_x86_64.tar.gz"
      sha256 "8d84770a4f4c248ea17e0ac078ce2df970c688febb1816c18ad25c4b99b8542f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrayFlash/go-releaser/releases/download/v0.1.4/go-releaser_0.1.4_Linux_arm64.tar.gz"
      sha256 "bc9c2e21b566668cdb0bb4df0975f9383db5450a712a931d191b05ea5e1f5f04"
    end
  end

  depends_on "git"

  def install
    bin.install "go-releaser"
  end
end
