# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kirkup < Formula
  desc "CLI tool to track and retro your AI coding agent activity"
  homepage "https://github.com/GrayFlash/kirkup-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GrayFlash/kirkup-cli/releases/download/v0.1.2/kirkup-cli_darwin_amd64.tar.gz"
      sha256 "c318d09b185ba15b463abe9e8aa010cbed43f7493a402a71d613bf6849234866"

      define_method(:install) do
        bin.install "kirkup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GrayFlash/kirkup-cli/releases/download/v0.1.2/kirkup-cli_darwin_arm64.tar.gz"
      sha256 "e052f3e1ddc51d10190cccf378bebdd54902ff59bb301cc7a1350a44468934c1"

      define_method(:install) do
        bin.install "kirkup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrayFlash/kirkup-cli/releases/download/v0.1.2/kirkup-cli_linux_amd64.tar.gz"
      sha256 "f6a7c52b00c5c526a538f0681cf543c0a3aa7892e49b739cec7763647b8c85c4"
      define_method(:install) do
        bin.install "kirkup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GrayFlash/kirkup-cli/releases/download/v0.1.2/kirkup-cli_linux_arm64.tar.gz"
      sha256 "3699de54e6fc5c3b5e4e9f17c55284620e24008b713665b30efb2587c32f7542"
      define_method(:install) do
        bin.install "kirkup"
      end
    end
  end

  test do
    system "#{bin}/kirkup", "--version"
  end
end
